"use client";
import { FormEvent, useMemo, useState } from "react";
type Handover={id:number;title:string;detail:string;time:string;owner:string;status:"Khẩn cấp"|"Đang xử lý"|"Chờ xác nhận"|"Hoàn tất";icon:string};
const initialItems:Handover[]=[
{id:1,title:"Khách phòng 512 yêu cầu xe sân bay",detail:"Đón tại sảnh lúc 07:00 · Đã báo giá 380.000đ",time:"Còn 25 phút",owner:"Ca đêm · Minh Anh",status:"Khẩn cấp",icon:"!"},
{id:2,title:"P502 báo điều hòa chưa đủ lạnh",detail:"Kỹ thuật đã kiểm tra lần 1, cần theo dõi thêm",time:"Cập nhật 06:20",owner:"Ca đêm · Hoàng",status:"Đang xử lý",icon:"❄"},
{id:3,title:"Đối soát tiền mặt ca đêm",detail:"Tiền mặt 12.500.000đ · Chứng từ đã đủ",time:"Tạo lúc 06:35",owner:"Ca đêm · Minh Anh",status:"Chờ xác nhận",icon:"₫"},
{id:4,title:"Wake-up call phòng 308",detail:"Khách đã nhận cuộc gọi lúc 05:30",time:"Hoàn tất 05:32",owner:"Ca đêm · Hoàng",status:"Hoàn tất",icon:"✓"}];
const filters=["Tất cả","Khẩn cấp","Đang xử lý","Chờ xác nhận","Hoàn tất"];
export default function Home(){
const [activeFilter,setActiveFilter]=useState("Tất cả"),[items,setItems]=useState(initialItems),[showForm,setShowForm]=useState(false),[toast,setToast]=useState(""),[activeNav,setActiveNav]=useState("Bàn giao");
const visibleItems=useMemo(()=>activeFilter==="Tất cả"?items:items.filter(i=>i.status===activeFilter),[activeFilter,items]),openCount=items.filter(i=>i.status!=="Hoàn tất").length;
function notify(message:string){setToast(message);window.setTimeout(()=>setToast(""),2200)}
function submitHandover(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setItems(current=>[{id:Date.now(),title:String(form.get("title")||"Nội dung bàn giao mới"),detail:String(form.get("detail")||"Cần ca sáng tiếp tục theo dõi"),time:"Vừa xong",owner:"Ca đêm · Bạn",status:"Chờ xác nhận",icon:"↗"},...current]);setActiveFilter("Tất cả");setShowForm(false);notify("Đã thêm nội dung bàn giao")}
return <main className="app-shell">
<header className="topbar"><div className="topline"><button className="avatar" aria-label="Mở hồ sơ">MA</button><div className="hotel"><span>Khách sạn Aurora</span><small>Thứ Bảy, 11/07/2026</small></div><button className="bell" aria-label="Thông báo">♢<b>3</b></button></div><div className="shift-title"><div><span className="live-dot"/> CA ĐÊM → CA SÁNG</div><h1>Sổ bàn giao ca</h1><p>06:45 · Người giao: Minh Anh</p></div><div className="summary"><div><strong>{openCount}</strong><span>Cần tiếp nhận</span></div><i/><div><strong>{items.filter(i=>i.status==="Khẩn cấp").length}</strong><span>Khẩn cấp</span></div><i/><div><strong>{items.filter(i=>i.status==="Hoàn tất").length}</strong><span>Hoàn tất</span></div></div></header>
<section className="content"><div className="section-heading"><div><h2>Nội dung bàn giao</h2><p>{openCount} việc cần ca sáng tiếp nhận</p></div><button className="add-button" onClick={()=>setShowForm(true)}><span>＋</span> Thêm mới</button></div><div className="filters">{filters.map(f=><button key={f} className={activeFilter===f?"active":""} onClick={()=>setActiveFilter(f)}>{f}{f==="Tất cả"&&<em>{items.length}</em>}</button>)}</div><div className="card-list">{visibleItems.map(item=>{const tone=item.status==="Khẩn cấp"?"red":item.status==="Đang xử lý"?"blue":item.status==="Hoàn tất"?"green":"amber";return <article className={`handover-card ${tone}`} key={item.id}><div className="card-icon">{item.icon}</div><div className="card-body"><div className="card-title"><h3>{item.title}</h3><span>{item.status}</span></div><p className="detail">{item.detail}</p><div className="meta"><span>◷ {item.time}</span><span>♙ {item.owner}</span></div>{item.status!=="Hoàn tất"&&<button className="action-link" onClick={()=>notify(`Đã mở: ${item.title}`)}>Xem chi tiết <b>→</b></button>}</div></article>})}{!visibleItems.length&&<div className="empty">Không có nội dung ở trạng thái này.</div>}</div><button className="confirm-button" onClick={()=>{setItems(items.map(i=>i.status==="Chờ xác nhận"?{...i,status:"Hoàn tất"}:i));notify("Ca sáng đã xác nhận nhận bàn giao")}}><span>✓</span><div><strong>Xác nhận nhận bàn giao</strong><small>Ca sáng · Nguyễn Thu Hà</small></div></button><p className="sync-note">● Dữ liệu đã đồng bộ · 06:45</p></section>
<nav className="bottom-nav">{[["⌂","Bàn giao"],["☑","Việc tồn đọng"],["▤","Báo cáo"],["♢","Thông báo"],["⚙","Cài đặt"]].map(([icon,label])=><button key={label} className={activeNav===label?"active":""} onClick={()=>{setActiveNav(label);if(label!=="Bàn giao")notify(`${label} đang được chuẩn bị`)}}><span>{icon}</span><small>{label}</small>{label==="Thông báo"&&<b>3</b>}</button>)}</nav>
{showForm&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setShowForm(false)}><form className="sheet" onSubmit={submitHandover}><div className="sheet-handle"/><div className="sheet-title"><div><small>BÀN GIAO CA</small><h2>Thêm nội dung mới</h2></div><button type="button" onClick={()=>setShowForm(false)}>×</button></div><label>Tiêu đề<input name="title" required placeholder="Ví dụ: Khách phòng 302 cần hỗ trợ" autoFocus/></label><label>Chi tiết<textarea name="detail" required placeholder="Thông tin ca sau cần tiếp tục xử lý..." rows={4}/></label><label>Mức độ<select name="priority"><option>Chờ xác nhận</option><option>Khẩn cấp</option><option>Đang xử lý</option></select></label><button className="save-button" type="submit">Lưu vào sổ bàn giao</button></form></div>}{toast&&<div className="toast"><span>✓</span>{toast}</div>}</main>}
