begin;
do $$declare t text;begin foreach t in array array['organizations','branches','profiles','roles','permissions','role_permissions','branch_memberships','shift_definitions','shift_instances','shift_assignments','handovers','handover_participants','handover_sections','handover_items','handover_amendments','room_issues','guest_notes','bookings','booking_debts','cash_handovers','cash_handover_items','finance_discrepancies','reconciliation_records','assets','asset_handovers','lost_found_items','pending_tasks','checklist_templates','checklist_template_items','checklist_results','confirmations','attachments','notifications','notification_preferences','report_exports','audit_logs','outbox_events'] loop execute format('alter table %I enable row level security',t);end loop;end$$;
create policy branches_member_read on branches for select to authenticated using(id in(select current_branch_ids()));
create policy profiles_colleague_read on profiles for select to authenticated using(id=auth.uid() or exists(select 1 from branch_memberships mine join branch_memberships theirs on theirs.branch_id=mine.branch_id where mine.profile_id=auth.uid() and theirs.profile_id=profiles.id and mine.is_active and theirs.is_active));
create policy memberships_self_read on branch_memberships for select to authenticated using(profile_id=auth.uid() or branch_id in(select current_branch_ids()));
create policy shifts_member_read on shift_instances for select to authenticated using(branch_id in(select current_branch_ids()));
create policy handovers_member_read on handovers for select to authenticated using(branch_id in(select current_branch_ids()));
create policy participants_member_read on handover_participants for select to authenticated using(branch_id in(select current_branch_ids()));
create policy items_member_read on handover_items for select to authenticated using(exists(select 1 from handovers h where h.id=handover_id and h.branch_id in(select current_branch_ids())));
create policy tasks_member_read on pending_tasks for select to authenticated using(branch_id in(select current_branch_ids()));
create policy notifications_own_read on notifications for select to authenticated using(profile_id=auth.uid());
create policy audit_manager_read on audit_logs for select to authenticated using(branch_id in(select current_branch_ids()) and exists(select 1 from branch_memberships bm join roles r on r.id=bm.role_id where bm.profile_id=auth.uid() and bm.branch_id=audit_logs.branch_id and r.code in('SHIFT_LEADER','BRANCH_MANAGER','REGIONAL_MANAGER','INSPECTOR','ADMIN')));
-- Mutations normally use the NestJS backend. No authenticated direct-write policies are created for business tables.
insert into storage.buckets(id,name,public) values('handover-attachments','handover-attachments',false),('room-issues','room-issues',false),('cash-documents','cash-documents',false),('lost-found','lost-found',false),('signatures','signatures',false),('report-exports','report-exports',false) on conflict(id) do update set public=false;
create policy private_storage_member_read on storage.objects for select to authenticated using(bucket_id in('handover-attachments','room-issues','cash-documents','lost-found','signatures','report-exports') and (storage.foldername(name))[1] in(select organization_id::text from profiles where id=auth.uid()));
alter publication supabase_realtime add table handovers;alter publication supabase_realtime add table pending_tasks;alter publication supabase_realtime add table notifications;alter publication supabase_realtime add table shift_instances;
commit;
